// Code generated by eksd-gen. DO NOT EDIT.

package eksd

var table = map[string]Release{
	"1.29": {
		EKSVersion:  "1.29",
		Channel:     "1-29",
		Number:      60,
		KubeVersion: "v1.29.15",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-29/releases/60/artifacts/kubernetes/v1.29.15/kubernetes-server-linux-amd64.tar.gz", SHA256: "4507625bd618a277644c63de534e67db58840a668091b478220c4940285f35c8"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-29/releases/60/artifacts/kubernetes/v1.29.15/kubernetes-server-linux-arm64.tar.gz", SHA256: "65a2cf9a43674a4faa8e464383dcd04dad2b1e66bc53069a2617edb0fec3616c"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.12.4-eks-1-29-60",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.29.15-eks-1-29-60",
	},
	"1.30": {
		EKSVersion:  "1.30",
		Channel:     "1-30",
		Number:      58,
		KubeVersion: "v1.30.14",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-30/releases/58/artifacts/kubernetes/v1.30.14/kubernetes-server-linux-amd64.tar.gz", SHA256: "54e3c46acbf270b2b35174c418845cba393b2243a99fb115d4254e5dfa90aa98"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-30/releases/58/artifacts/kubernetes/v1.30.14/kubernetes-server-linux-arm64.tar.gz", SHA256: "27222483015b9adab36c09cef9b62d1cdf28f21a4b54fd55698c00037312ad96"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.12.4-eks-1-30-58",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.30.14-eks-1-30-58",
	},
	"1.31": {
		EKSVersion:  "1.31",
		Channel:     "1-31",
		Number:      47,
		KubeVersion: "v1.31.14",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-31/releases/47/artifacts/kubernetes/v1.31.14/kubernetes-server-linux-amd64.tar.gz", SHA256: "2460e2e52b91b98eed3b00c005f7ec21c76824a56bab807b4bbc86d066fa6a9c"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-31/releases/47/artifacts/kubernetes/v1.31.14/kubernetes-server-linux-arm64.tar.gz", SHA256: "884e8edd11cc7ec8a18e5442ee64a095188133b863099ec9475d00b0c2e0d5d6"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.12.4-eks-1-31-47",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.31.14-eks-1-31-47",
	},
	"1.32": {
		EKSVersion:  "1.32",
		Channel:     "1-32",
		Number:      40,
		KubeVersion: "v1.32.13",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-32/releases/40/artifacts/kubernetes/v1.32.13/kubernetes-server-linux-amd64.tar.gz", SHA256: "85f578ac5b167aced564d341eb2de2d0ec958d173ae74f547b4bbb3cde32206d"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-32/releases/40/artifacts/kubernetes/v1.32.13/kubernetes-server-linux-arm64.tar.gz", SHA256: "8858668315a2155e84cfbe2db24b446d274e7977a82a3dd41f876d9bda668076"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.12.4-eks-1-32-40",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.32.13-eks-1-32-40",
	},
	"1.33": {
		EKSVersion:  "1.33",
		Channel:     "1-33",
		Number:      30,
		KubeVersion: "v1.33.13",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-33/releases/30/artifacts/kubernetes/v1.33.13/kubernetes-server-linux-amd64.tar.gz", SHA256: "8571084ee767b0f2b3d09b88d6b5aefb5149a92b07cd6f2ddf07d7e1d47e88b9"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-33/releases/30/artifacts/kubernetes/v1.33.13/kubernetes-server-linux-arm64.tar.gz", SHA256: "e9a8d847563960ae313d1e4c2b046c1d2ffcf72558222780572b7eecf01e7daf"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.14.3-eks-1-33-30",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.33.13-eks-1-33-30",
	},
	"1.34": {
		EKSVersion:  "1.34",
		Channel:     "1-34",
		Number:      21,
		KubeVersion: "v1.34.9",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-34/releases/21/artifacts/kubernetes/v1.34.9/kubernetes-server-linux-amd64.tar.gz", SHA256: "d69b1668e8079597f5389b8c5c5b97c83a1e42cfbbe7dc06dec08fda6aa8fc4d"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-34/releases/21/artifacts/kubernetes/v1.34.9/kubernetes-server-linux-arm64.tar.gz", SHA256: "b9988326bf7ba43b340300b05a3b91b96b149859c475a43ffe6d557f3efa6527"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.14.3-eks-1-34-21",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.34.9-eks-1-34-21",
	},
	"1.35": {
		EKSVersion:  "1.35",
		Channel:     "1-35",
		Number:      12,
		KubeVersion: "v1.35.6",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-35/releases/12/artifacts/kubernetes/v1.35.6/kubernetes-server-linux-amd64.tar.gz", SHA256: "f29c0969f9cb7df9064ab33145a0eeaec03acc727468f51241fba2246fbe73c1"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-35/releases/12/artifacts/kubernetes/v1.35.6/kubernetes-server-linux-arm64.tar.gz", SHA256: "cae80dd6c31e4d9001a218aca453ed927957cf1b8e63df777e913a80f6cc6d41"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.14.3-eks-1-35-12",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.35.6-eks-1-35-12",
	},
	"1.36": {
		EKSVersion:  "1.36",
		Channel:     "1-36",
		Number:      6,
		KubeVersion: "v1.36.2",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-36/releases/6/artifacts/kubernetes/v1.36.2/kubernetes-server-linux-amd64.tar.gz", SHA256: "19bca528bfb2d98ac196a198e29b3226b34529133bb8de8c6e54fbd5ebe36bb4"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-36/releases/6/artifacts/kubernetes/v1.36.2/kubernetes-server-linux-arm64.tar.gz", SHA256: "15a1c077110067b672176c049783f7834fab6c0c39e9c54dde3a2c73cfabff22"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.14.3-eks-1-36-6",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.36.2-eks-1-36-6",
	},
}
