// Code generated by eksd-gen. DO NOT EDIT.

package eksd

var table = map[string]Release{
	"1.29": {
		EKSVersion:  "1.29",
		Channel:     "1-29",
		Number:      60,
		KubeVersion: "v1.29.15",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-29/releases/60/artifacts/kubernetes/v1.29.15/kubernetes-server-linux-amd64.tar.gz", SHA256: "4507625bd618a277644c63de534e67db58840a668091b478220c4940285f35c8"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-29/releases/60/artifacts/kubernetes/v1.29.15/kubernetes-server-linux-arm64.tar.gz", SHA256: "65a2cf9a43674a4faa8e464383dcd04dad2b1e66bc53069a2617edb0fec3616c"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.12.4-eks-1-29-60",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.29.15-eks-1-29-60",
	},
	"1.30": {
		EKSVersion:  "1.30",
		Channel:     "1-30",
		Number:      57,
		KubeVersion: "v1.30.14",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-30/releases/57/artifacts/kubernetes/v1.30.14/kubernetes-server-linux-amd64.tar.gz", SHA256: "c278c4f98c3c53375fffcb46ced13608578a249a63701c2fc43ebb26c47bd1ec"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-30/releases/57/artifacts/kubernetes/v1.30.14/kubernetes-server-linux-arm64.tar.gz", SHA256: "d7b1e359f44cacf5c21b6435c954a61af43f0b888c4a5ff93e08ebfb5c38ffea"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.12.4-eks-1-30-57",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.30.14-eks-1-30-57",
	},
	"1.31": {
		EKSVersion:  "1.31",
		Channel:     "1-31",
		Number:      46,
		KubeVersion: "v1.31.14",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-31/releases/46/artifacts/kubernetes/v1.31.14/kubernetes-server-linux-amd64.tar.gz", SHA256: "425a73d03ef0705daa6920c8d44a7be0cff8bd22510b1f0201317eba4695a657"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-31/releases/46/artifacts/kubernetes/v1.31.14/kubernetes-server-linux-arm64.tar.gz", SHA256: "d85f56ff0b9de26a1a6622d88bdf52da02881744cec2bc65ad21ec2e2bb50088"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.12.4-eks-1-31-46",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.31.14-eks-1-31-46",
	},
	"1.32": {
		EKSVersion:  "1.32",
		Channel:     "1-32",
		Number:      39,
		KubeVersion: "v1.32.13",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-32/releases/39/artifacts/kubernetes/v1.32.13/kubernetes-server-linux-amd64.tar.gz", SHA256: "699ba0941d8a4357a8558717b380c612b7f2b7e0af3652664c690bde84600f60"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-32/releases/39/artifacts/kubernetes/v1.32.13/kubernetes-server-linux-arm64.tar.gz", SHA256: "b68853dd94155e46412dc15d93d72481ce44713c445774d508146bfda8d94815"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.12.4-eks-1-32-39",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.32.13-eks-1-32-39",
	},
	"1.33": {
		EKSVersion:  "1.33",
		Channel:     "1-33",
		Number:      29,
		KubeVersion: "v1.33.13",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-33/releases/29/artifacts/kubernetes/v1.33.13/kubernetes-server-linux-amd64.tar.gz", SHA256: "73408de83a0a5d08830aa54f4033018b83e5e0e16e0ce75a2b0d554ff3197c06"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-33/releases/29/artifacts/kubernetes/v1.33.13/kubernetes-server-linux-arm64.tar.gz", SHA256: "8514e089dc6fcb436504d472cfb6cfc31c5d22087fc71c8305166b59dd77d7af"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.14.2-eks-1-33-29",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.33.13-eks-1-33-29",
	},
	"1.34": {
		EKSVersion:  "1.34",
		Channel:     "1-34",
		Number:      20,
		KubeVersion: "v1.34.9",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-34/releases/20/artifacts/kubernetes/v1.34.9/kubernetes-server-linux-amd64.tar.gz", SHA256: "73ea047b4323d37e306966bde9f635c268aeed2fd1b200952a02cdf85532c077"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-34/releases/20/artifacts/kubernetes/v1.34.9/kubernetes-server-linux-arm64.tar.gz", SHA256: "a401281a27c4560672e3de9a6c742136332943490693c95d8e5ff1a94579c04e"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.14.2-eks-1-34-20",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.34.9-eks-1-34-20",
	},
	"1.35": {
		EKSVersion:  "1.35",
		Channel:     "1-35",
		Number:      11,
		KubeVersion: "v1.35.6",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-35/releases/11/artifacts/kubernetes/v1.35.6/kubernetes-server-linux-amd64.tar.gz", SHA256: "080272de40bb76286211991d6d2011fe199182856ee34dafca3fecb12c202634"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-35/releases/11/artifacts/kubernetes/v1.35.6/kubernetes-server-linux-arm64.tar.gz", SHA256: "d4e79e37df8818006e3a84b956646334e9432ad6b507ab4dbc67ca72b3b7210c"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.14.2-eks-1-35-11",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.35.6-eks-1-35-11",
	},
	"1.36": {
		EKSVersion:  "1.36",
		Channel:     "1-36",
		Number:      5,
		KubeVersion: "v1.36.2",
		ServerTarball: map[string]Asset{
			"amd64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-36/releases/5/artifacts/kubernetes/v1.36.2/kubernetes-server-linux-amd64.tar.gz", SHA256: "e64d5ec5740472a2945fdbc1e43b4c215f03c25de5a904c9c47740b73ce20d1d"},
			"arm64": {URI: "https://distro.eks.amazonaws.com/kubernetes-1-36/releases/5/artifacts/kubernetes/v1.36.2/kubernetes-server-linux-arm64.tar.gz", SHA256: "b605313f0586c3488c6771b4bc6b9e53c8361cad05d39270a92209d600ff8c42"},
		},
		CoreDNSImage:   "public.ecr.aws/eks-distro/coredns/coredns:v1.14.2-eks-1-36-5",
		KubeProxyImage: "public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.36.2-eks-1-36-5",
	},
}
