// Command eksd-gen fetches, for each EKS Kubernetes minor version fjord
// supports, the latest published EKS-D release manifest and regenerates
// internal/eksd/generated_table.go from the result.
package main

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/sivchari/fjord/internal/eksd"
)

// supportedMinors lists the EKS Kubernetes minor versions the generated
// table must carry an entry for.
var supportedMinors = []string{
	"1.29", "1.30", "1.31", "1.32", "1.33", "1.34", "1.35", "1.36",
}

// outputPath is the repository-relative path of the generated table.
const outputPath = "internal/eksd/generated_table.go"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	client := &http.Client{Timeout: 30 * time.Second}

	releases, err := fetchReleases(ctx, client)
	if err != nil {
		return err
	}

	src, err := render(releases)
	if err != nil {
		return fmt.Errorf("rendering generated table: %w", err)
	}

	if err := os.WriteFile(outputPath, src, 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", outputPath, err)
	}

	return nil
}

// fetchReleases resolves the latest EKS-D release for every entry in
// supportedMinors.
func fetchReleases(ctx context.Context, client *http.Client) (map[string]eksd.Release, error) {
	releases := make(map[string]eksd.Release, len(supportedMinors))

	for _, minor := range supportedMinors {
		channel := strings.ReplaceAll(minor, ".", "-")

		number, err := eksd.LatestNumber(ctx, client, eksd.DefaultBaseURL, channel)
		if err != nil {
			return nil, fmt.Errorf("finding latest eks-d release number for %s: %w", minor, err)
		}

		release, err := eksd.Fetch(ctx, client, eksd.DefaultBaseURL, channel, number)
		if err != nil {
			return nil, fmt.Errorf("fetching eks-d release for %s eks-%d: %w", minor, number, err)
		}

		releases[minor] = *release

		_, _ = fmt.Fprintf(os.Stdout, "resolved %s -> eks-%d (%s)\n", minor, number, release.KubeVersion)
	}

	return releases, nil
}

// render generates the Go source of internal/eksd/generated_table.go for
// releases.
func render(releases map[string]eksd.Release) ([]byte, error) {
	minors := make([]string, 0, len(releases))
	for minor := range releases {
		minors = append(minors, minor)
	}

	sort.Strings(minors)

	var buf bytes.Buffer

	buf.WriteString("// Code generated by eksd-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package eksd\n\n")
	buf.WriteString("var table = map[string]Release{\n")

	for _, minor := range minors {
		release := releases[minor]
		writeReleaseEntry(&buf, minor, &release)
	}

	buf.WriteString("}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}

	return src, nil
}

// writeReleaseEntry writes the map entry for minor/release to buf.
func writeReleaseEntry(buf *bytes.Buffer, minor string, release *eksd.Release) {
	fmt.Fprintf(buf, "\t%q: {\n", minor)
	fmt.Fprintf(buf, "\t\tEKSVersion: %q,\n", release.EKSVersion)
	fmt.Fprintf(buf, "\t\tChannel: %q,\n", release.Channel)
	fmt.Fprintf(buf, "\t\tNumber: %d,\n", release.Number)
	fmt.Fprintf(buf, "\t\tKubeVersion: %q,\n", release.KubeVersion)
	buf.WriteString("\t\tServerTarball: map[string]Asset{\n")

	arches := make([]string, 0, len(release.ServerTarball))
	for arch := range release.ServerTarball {
		arches = append(arches, arch)
	}

	sort.Strings(arches)

	for _, arch := range arches {
		asset := release.ServerTarball[arch]
		fmt.Fprintf(buf, "\t\t\t%q: {URI: %q, SHA256: %q},\n", arch, asset.URI, asset.SHA256)
	}

	buf.WriteString("\t\t},\n")
	fmt.Fprintf(buf, "\t\tCoreDNSImage: %q,\n", release.CoreDNSImage)
	fmt.Fprintf(buf, "\t\tKubeProxyImage: %q,\n", release.KubeProxyImage)
	buf.WriteString("\t},\n")
}
